identity = {
	"ADBL" : 'Agriculture Development Bank Limited',
	"CBL" : 'Civil Bank Ltd',
	"CTBNL" : 'Commerz and Trust Bank Nepal Ltd.',
	"CZBIL" : 'Citizen Bank International Limited',
	"EBL" : 'Everest Bank Limited',
	"GBIME" : 'Global IME Bank Limited',
	"GRAND" : 'Grand Bank Nepal Limited',
	"HBL" : 'Himalayan Bank Limited',
	"JBNL" : 'Janata Bank Nepal Ltd.',
	"KBL" : 'Kumari Bank Limited',
	"KIST" : 'KIST Bank Limited',
	"LBL" : 'Laxmi Bank Limited',
	"LUBL" : 'Lumbini Bank Limited',
	"MBL" : 'Machhapuchhre Bank Limited',
	"MEGA" : 'Mega Bank Nepal Ltd.',
	"NABIL" : 'Nabil Bank Limited',
	"NBB" : 'Nepal Bangladesh Bank Limited',
	"NBL" : 'Nepal Bank Limited',
	"NCCB" : 'Nepal Credit And Commercial Bank Limited',
	"NIB" : 'Nepal Investment Bank Limited',
	"NICA" : 'NIC Asia Bank Ltd.',
	"NMB" : 'NMB Bank Limited',
	"PCBL" : 'Prime Commercial Bank Ltd.',
	"SANIMA" : 'Sanima Bank Limited',
	"SBI" : 'Nepal SBI Bank Limited',
	"SBL" : 'Siddhartha Bank Limited',
	"SCB" : 'Standard Chartered Bank Limited',
	"SRBL" : 'Sunrise Bank Limited',
	"CCBL" : 'Century Commercial Bank Ltd.',
	"BOAN" : 'Bank of Asia Nepal Limited',
	"PRVU" : 'Prabhu Bank Limited',
	"RBB" : 'Rastriya Banijya Bank Limited',
	"BOKL" : 'Bank of Kathmandu Ltd.',
	"BOKB2076" : 'Bank of Kathmandu - 2076',
	"CZBILB2077" : 'Citizens Bank Bond 2077',
	"EBLB2079" : 'Everest Bank Limited--2079',
	"GBIMEB2076" : 'Global IME Bank -2076',
	"HBLB2072" : 'Himalayan Bank Limited 2072',
	"HBLB2077" : 'Himalayan Bank Limited 2077',
	"LBLB2072" : 'Laxmi Bank Limited 2072',
	"LBLB2076" : 'Laxmi Bank -2076',
	"NABILB2075" : 'Nabil Bank Limited Bond 2075',
	"NIBB2071" : 'Nepal Investment Bank Bond 2071',
	"NIBB2072" : 'Nepal Investment Bank Limited Bond 2072',
	"NIBB2075" : 'Nepal Investment Bank Limited Bond 2075',
	"NIBB2077" : 'Nepal Investment Bank Bond 2077',
	"SBIB2078" : 'Nepal SBI Bank -2078',
	"SBIB2079" : 'Nepal SBI Bank - 2079',
	"SBL2072" : 'Siddhartha Bank-2072',
	"SBLB2075" : 'Siddhartha Bank Ltd.-2075',
	"SBLB2076" : 'Siddhartha Bank Ltd. Bond -2076',
	"ALDBL" : 'Alpine Development Bank Limited',
	"APEX" : 'Apex Development Bank Ltd.',
	"ARDBL" : 'Araniko Development Bank Limited',
	"AXIS" : 'Axis Development Bank Limited',
	"BBBL" : 'Bhrikuti Vikash Bank Limited',
	"BBBLN" : 'Bagheshwori Development Bank Limited',
	"BGDBL" : 'Bagmati Development Bank Ltd.',
	"BHBL" : 'Bhargav Bikash Bank Ltd.',
	"BLDBL" : 'Biratlaxmi Bikas Bank Limited',
	"BRTBL" : 'Bright Development Bank Ltd',
	"BSBL" : 'Bishwa Bikas Bank Limited',
	"BUDBL" : 'Business Universal Development Bank Ltd.',
	"CDBL" : 'City Development Bank Limited',
	"CEDBL" : 'Clean Energy Development Bank Limited',
	"CIVIC" : 'Civic Development Bank Ltd',
	"CNDBL" : 'Country Development Bank Ltd.',
	"CORBL" : 'Corporate Development Bank Limited',
	"CSDBL" : 'Cosmos Development Bank Ltd.',
	"EDBL" : 'Excel Development Bank Ltd.',
	"GABL" : 'Gaumukhee Bikas Bank Ltd.',
	"GBBL" : 'Garima Bikas Bank Limited',
	"GDBL" : 'Gandaki Bikas Bank Limited',
	"GDBNL" : 'Gurkha Development Bank Limited',
	"GSDBL" : 'Gaurishankar Development Bank Ltd.',
	"HAMRO" : 'Hamro Bikas Bank Ltd.',
	"HBDL" : 'H & B Development Bank Ltd.',
	"IDBL" : 'Infrastructure Development Bank Ltd.',
	"INDB" : 'Innovative Development Bank Ltd.',
	"INDBL" : 'International Development Bank Ltd',
	"JBBL" : 'Jyoti Bikas Bank Limited',
	"JHBL" : 'Jhimruk Bikas Bank Ltd.',
	"KADBL" : 'Kanchan Development Bank Limited',
	"KBBL" : 'Kailash Bikas Bank Ltd.',
	"KDBL" : 'Kasthamandap Development Bank Limited',
	"KEBL" : 'Kabeli Bikas Bank Limited',
	"KHDBL" : 'Khandbari Development Bank Ltd',
	"KKBL" : 'Kakre Bihar Bikash Bank Ltd',
	"KMBL" : 'Kamana Bikas Bank Limited',
	"KNBL" : 'Kankai Bikas Bank Ltd.',
	"KRBL" : 'Karnali Development Bank Limited',
	"MBBL" : 'Mahakali Bikas Bank Limited',
	"MDB" : 'Miteri Development Bank Limited',
	"MDBL" : 'Malika Bikas Bank Limited',
	"METRO" : 'Metro Development Bank Limited',
	"MGBL" : 'Madhyamanchal Gramin Development Bank Ltd.',
	"MIDBL" : 'Mission Development Bank Ltd.',
	"MNBBL" : 'Muktinath Bikas Bank Ltd.',
	"MSBBL" : 'Manaslu Bikas Bank Ltd.',
	"MTBL" : 'Matribhumi Development Bank Ltd.',
	"NABBC" : 'Narayani Development Bank Limited',
	"NCDB" : 'Nepal Community Development Bank Ltd.',
	"NCDBL" : 'Nepal Consumer Development Bank Ltd.',
	"NDB" : 'Nepal Development Bank Limited',
	"NDEP" : 'NDEP Development Bank Limited',
	"NGBL" : 'Nilgiri Bikas Bank Limited',
	"NIDC" : 'NIDC Development Bank Ltd.',
	"PADBL" : 'Pacific Development Bank Limited',
	"PBSL" : 'Pathibhara Bikas Bank Limited',
	"PDB" : 'Public Development Bank Limited',
	"PDBL" : 'Paschimanchal Bikash Bank Limited',
	"PGBBL" : 'Pashchimanchal Grameen Bikas Bank Ltd.',
	"PGBL" : 'Purwanchal Grameen Bikash Bank Limited',
	"PRBBL" : 'Prabhu Bikas Bank Limited',
	"PRDBL" : 'Professional Diyalo Bikas Bank Ltd.',
	"PURBL" : 'Purnima Bikas Bank Ltd.',
	"RDBL" : 'Rising Development Bank Ltd.',
	"SADBL" : 'Shangrila Development Bank Ltd.',
	"SBBLJ" : 'Sahayogi Bikas Bank Limited',
	"SDBL" : 'Siddhartha Development Bank Ltd.',
	"SEWA" : 'Sewa Bikas Bank Limited',
	"SHINE" : 'Shine Resunga Development Bank Ltd.',
	"SINDU" : 'Sindhu Bikash Bank Ltd',
	"SUBBL" : 'Subhechha Bikas Bank Limited',
	"SUPRME" : 'Supreme Development Bank Ltd.',
	"TBBL" : 'Triveni Bikas Bank Limited',
	"TDBL" : 'Tourism Development Bank Limited',
	"TNBL" : 'Tinau Development Bank Limited',
	"VBBL" : 'Vibor Bikas Bank Limited',
	"WDBL" : 'Western Development Bank Limited',
	"YETI" : 'Yeti Development Bank Limited',
	"ACEDBL" : 'Ace Development Bank Ltd.',
	"GULMI" : 'Gulmi Bikas Bank Ltd.',
	"PRBL" : 'Professional Bikas Bank Ltd.',
	"RARA" : 'Rara Bikas Bank Limited',
	"RBSL" : 'Resunga Bikas Bank Limited',
	"UBBL" : 'Udhyam Bikas Bank Limited',
	"REDBL" : 'Reliable Development Bank Limited',
	"MMDBL" : 'Mount Makalu Development Bank Ltd.',
	"EKBL" : 'Ekata Bikas Bank Ltd.',
	"SHBL" : 'Sahara Bikas Bank Ltd.',
	"KCDBL" : 'Kalinchowk Development Bank Ltd.',
	"SODBL" : 'Society Development Bank Ltd.',
	"RBBBL" : 'Raptibheri Bikas Bank Ltd.',
	"DBBL" : 'Deva Bikas Bank Limited',
	"FBBL" : 'Fewa Bikas Bank Limited',
	"ILFCM" : 'ILFCO Microfinance Bittiya Sanstha Ltd.',
	"GRDBL" : 'Green Development Bank Ltd.',
	"SAJHA" : 'Sajha Bikas Bank Ltd.',
	"SKDBL" : 'Saptakoshi Development Bank Ltd.',
	"CVMF" : 'Clean Village Microfinance Bittiya Sanstha Ltd.',
	"ODBL" : 'Om Development Bank Ltd.',
	"VSDBL" : 'Vibor Society Development Bank Limited',
	"MLBL" : 'Mahalaxmi Bikas Bank Ltd.',
	"LBBL" : 'Lumbini Bikas Bank Ltd.',
	"KSBBL" : 'Kamana Sewa Bikas Bank Limited',
	"CFCL" : 'Central Finance Co. Ltd.',
	"CFL" : 'Crystal Finance Ltd.',
	"CMB" : 'Capital Merchant Bank & Finance Co. Ltd.',
	"CMBSL" : 'Civil Merchant Bittiya Santha Ltd.',
	"EFL" : 'Everest Finance Ltd.',
	"FFCL" : 'Fewa Finance Co. Ltd.',
	"GFCL" : 'Goodwill Finance Co. Ltd.',
	"GFL" : 'General Finance Ltd.',
	"GMFIL" : 'Guheshowori Merchant Bank & Finance Co. Ltd.',
	"HAMA" : 'Hama Merchant & Finance Ltd.',
	"HFL" : 'Himalayan Finance Limited (Bittiya Sanstha)',
	"ICFC" : 'ICFC Finance Limited',
	"IFIL" : 'Imperial Financial Inst. Ltd.',
	"ILFC" : 'International Leasing & Finance Co. Ltd.',
	"JEFL" : 'Jebils Finance Ltd.',
	"JFL" : 'Janaki Finance Ltd.',
	"KAFIL" : 'Kaski Finance Limited',
	"KFL" : 'Kathmandu Finance Ltd.',
	"LFC" : 'Lalitpur Finance Ltd.',
	"LFLC" : 'Lumbini Finance Ltd.',
	"MFIL" : 'Manjushree Finance Ltd.',
	"MFL" : 'Maha Laxmi Finance Limited',
	"MPFL" : 'Multipurpose Finance Company Limited',
	"NABB" : 'Nepal Aawas Finance Limited',
	"NBSL" : 'Namaste Bittiya Sanstha Ltd.',
	"NCM" : 'NIDC Capital Markets Ltd.',
	"NDFL" : 'Nava Durga Finance Co. Ltd.',
	"NEFL" : 'Nepal Express Finance Ltd.',
	"NFS" : 'Nepal Finance Ltd.',
	"NHMF" : 'Nepal Housing & Merchant Finance Ltd.',
	"NNFC" : 'Narayani National Finance Limited',
	"NSM" : 'Nepal Share Markets Ltd.',
	"OFL" : 'Om Finance Ltd.',
	"PFC" : 'Paschimanchal Finance Co. Ltd.',
	"PFCL" : 'Peoples Finance Ltd.',
	"PFCLL" : 'Premier Finance Co. Ltd.',
	"PFIL" : 'Prudential Finance Company Limited',
	"PFL" : 'Pokhara Finance Ltd.',
	"PFLBS" : 'Patan Finance Limited',
	"PRFL" : 'Prabhu Finance Company Limited',
	"PROFL" : 'ProgressiveFinance Limited',
	"RIBSL" : 'Reliable Finance Limited',
	"SETI" : 'Seti Finance Limited',
	"SFC" : 'Samjhana Finance Co. Ltd.',
	"SFFIL" : 'Shrijana Finance (Bittaya Sanstha)',
	"SFL" : 'Siddharth Finance Ltd.',
	"SIFC" : 'Shree Investment Finance Co. Ltd.',
	"SLFL" : 'Subha Laxmi Finance Company Limited',
	"SMBF" : 'Sagarmatha Merchant Banking & Finance Limited',
	"SYFL" : 'Synergy Finance Ltd.',
	"UFCL" : 'Union Finance Co. Ltd.',
	"UFIL" : 'Unique Finance Ltd.',
	"UFL" : 'United Finance Ltd.',
	"WMBF" : 'World Merchant Banking & Finance Ltd.',
	"ZFL" : 'Zenith Finance Limited',
	"AEFL" : 'Alpic Everest Finance Company Limited',
	"AFL" : 'Api Finance Limited',
	"BFIL" : 'Bhajuratna Finance & Saving Co. Ltd.',
	"BJFL" : 'Birgunj Finance Ltd.',
	"CMBF" : 'CMB Finance Limited',
	"GFLK" : 'Gorkha Finance Ltd.',
	"IMEFI" : 'IME Financial Institution',
	"LBFIL" : 'Lord Buddha Finance Limited',
	"NFL" : 'Narayani Finance Ltd.',
	"NBFL" : 'Nepal Bangladesh Finance & Leasing Co. Ltd.',
	"NSLMB" : 'Nepal Shree Lanka Merchant Banking & Finance Ltd',
	"SBSL" : 'Shikhar Finance Limited',
	"STFL" : 'Standard Finance Ltd.',
	"SDFL" : 'Suryadarshan Finance Company Limited',
	"SMF" : 'Swastik Merchant Finance Co. Ltd.',
	"UFLK" : 'Universal Finance Ltd.',
	"VFL" : 'Valley Finance Limited',
	"YFL" : 'Yeti Finance Limited',
	"RLFL" : 'Reliance Finance Ltd.',
	"BFCL" : 'Bhaktapur Finance Co. Ltd.',
	"SAFL" : 'Sagarmatha Finance Limited',
	"KMBSLP" : 'unknown',
	"GUFL" : 'Gurkhas Finance Ltd.',
	"BFC" : 'Best Finance Company Ltd.',
	"CEFL" : 'City Express Finance Co. Limited',
	"HATH" : 'Hathway Finance Company Limited',
	"NRBBR2067" : 'Bikash Rinpatra 2067',
	"NRBBR2067ga" : 'Bikash Rinpatra 2067 Ga',
	"NRBBR2067ka" : 'Bikash Rinpatra 2067 Ka',
	"NRBBR2067kha" : 'Bikash Rinpatra 2067 Kha',
	"NRBBR2069" : 'Bikash Rinpatra 2069',
	"NRBBR2071ka" : 'Bikash Rinpatra 2071 Ka',
	"NRBBR2071Kha" : 'Bikash Rinpatra 2071 Kha',
	"NRBBR2072" : 'Bikash Rinpatra 2072',
	"NRBBR2072ka" : 'Bikash Rinpatra 2072 Ka',
	"NRBBR2073 KA" : 'Bikash Rinpatra 2073 Ka',
	"NRBBR2075" : 'Bikash Rinpatra 2075',
	"NRBBR2075ka" : 'Bikash Rinpatra 2075 Ka',
	"NRBBR2076" : 'Bikash Rinpatra 2076',
	"NRBBR2076Ga" : 'Bikash Rinpatra 2076 Ga',
	"NRBBR2076ka" : 'Bikash Rinpatra 2076 Ka',
	"NRBBR2076Kha" : 'Bikash Rinpatra 2076 Kha',
	"OHL" : 'Oriental Hotels Limited',
	"SHL" : 'Soaltee Hotel Limited',
	"TRH" : 'Taragaon Regency Hotel Limited',
	"YHL" : 'Yak And Yeti Hotel Limited',
	"AHPC" : 'Arun Valley Hydropower Development Co. Ltd.',
	"BPCL" : 'Butwal Power Company Limited',
	"CHCL" : 'Chilime Hydropower Company Limited',
	"NHPC" : 'National Hydro Power Company Limited',
	"SHPC" : 'Sanima Mai Hydropower Ltd.',
	"RHPC" : 'Ridi Hydropower Development Company Ltd.',
	"AKPL" : 'Arun Kabeli Power Ltd.',
	"BARUN" : 'Barun Hydropower Co. Ltd.',
	"API" : 'Api Power Company Ltd.',
	"NGPL" : 'Ngadi Group Power Ltd.',
	"UMHL" : 'United Modi Hydropower Ltd.',
	"SPDL" : 'Synergy Power Development Ltd.',
	"KKHC" : 'Khanikhola Hydropower Co. Ltd.',
	"HPPL" : 'Himalayan Power Partner Ltd.',
	"DHPL" : 'Dibyashwori Hydropower Ltd.',
	"PMHL" : 'Panchakanya Mai Hydropower Limited',
	"CHL" : 'Chhyangdi Hydropower Ltd.',
	"NHDL" : 'Nepal Hydro Developers Ltd.',
	"RADHI" : 'Radhi Bidyut Company Ltd',
	"RRHP" : 'Rairang Hydropower Development Company Ltd.',
	"AIC" : 'Alliance Insurance Co. Ltd.',
	"EIC" : 'Everest Insurance Co. Ltd.',
	"HGI" : 'Himalayan General Insurance Co. Ltd',
	"LGIL" : 'Lumbini General Insurance Co. Ltd.',
	"NBIL" : 'NB Insurance Co. Ltd.',
	"NICL" : 'Nepal Insurance Co. Ltd.',
	"NIL" : 'Neco Insurance Co. Ltd.',
	"NLG" : 'NLG Insurance Company Ltd.',
	"PIC" : 'Premier Insurance Co. Ltd.',
	"PICL" : 'Prudential Insurance Co. Ltd.',
	"RBS" : 'Rastriya Beema Sansthan',
	"SIC" : 'Sagarmatha Insurance Co. Ltd.',
	"SICL" : 'Shikhar Insurance Co. Ltd.',
	"SIL" : 'Siddhartha Insurance Ltd.',
	"UIC" : 'United Insurance Co. (Nepal) Ltd.',
	"PRIN" : 'Prabhu Insurance Ltd.',
	"RBCL" : 'Rastriya Beema Company Limited',
	"NICLL" : 'National Insurance Company Limited',
	"IGI" : 'IME General Insurance Ltd.',
	"ALICL" : 'Asian Life Insurance Co. Limited',
	"GLICL" : 'Gurans Life Insurance Company Ltd.',
	"LICN" : 'Life Insurance Co. Nepal',
	"NLIC" : 'Nepal Life Insurance Co. Ltd.',
	"NLICL" : 'National Life Insurance Co. Ltd.',
	"PLIC" : 'Prime Life Insurance Company Limited',
	"SLICL" : 'Surya Life Insurance Company Limited',
	"AVU" : 'Arun Vanaspati Udhyog Limited',
	"BNL" : 'Bottlers Nepal (Balaju) Limited',
	"BNT" : 'Bottlers Nepal (Terai) Limited',
	"BSL" : 'Birat Shoe Limited',
	"BSM" : 'Butwal Spinning Mills Limited',
	"FHL" : 'Fleur Himalayan Limited',
	"GRU" : 'Gorakhkali Rubber Udhyog Limited',
	"HBT" : 'Harisiddhi Brick And Tiles Limited',
	"HDL" : 'Himalayan Distillery Limited',
	"JSM" : 'Jyoti Sinning Mills Limited',
	"NBBU" : 'Nepal Bitumin And Barrel Udhyog Limited',
	"NKU" : 'Nepal Khadya Udhyog Limited',
	"NLO" : 'Nepal Lube Oil Limited',
	"NVG" : 'Nepal Vanaspati Ghee Udhyog Limited',
	"RJM" : 'Raghupati Jute Mills Limited',
	"SBPP" : 'Shree Bhrikuti Pulp And Paper Limited',
	"SRS" : 'Shree Ram Sugar Mills Limited',
	"UNL" : 'Uniliver Nepal Limited',
	"BJM" : 'Biratnagar Jute Mills Limited',
	"HTL" : 'Himgiri Textile Industries Limited',
	"MSM" : 'Morang Sugar Mills Limited',
	"FHL" : 'Fleur Himalayan Limited',
	"CBBL" : 'Chhimek Laghubitta Bikas Bank Limited',
	"DDBL" : 'Deprosc Development Bank Limited',
	"FMDBL" : 'First Micro Finance Development Bank Ltd.',
	"KMCDB" : 'Kalika Microcredit Development Bank Ltd.',
	"NLBBL" : 'Nerude Laghubita Bikas Bank Limited',
	"NNLB" : 'Naya Nepal Laghubitta Bikas Bank Ltd.',
	"NUBL" : 'Nirdhan Utthan Bank Limited',
	"RMDC" : 'Rural Microfinance Development Centre Ltd.',
	"SKBBL" : 'Sana Kisan Bikas Bank Ltd',
	"SLBBL" : 'Swarojgar Laghu Bitta Bikas Bank Ltd.',
	"SMFDB" : 'Summit Micro Finance Development Bank Ltd.',
	"SWBBL" : 'Swabalamban Bikas Bank Limited',
	"MLBBL" : 'Mithila LaghuBitta Bikas Bank Ltd.',
	"NBBL" : 'NagBeli LaghuBitta Bikas Bank Ltd.',
	"LLBS" : 'Laxmi Laghubitta Bittiya Sanstha Ltd.',
	"MMFDB" : 'Mirmire Microfinance Development Bank Ltd.',
	"MSMBS" : 'Mahila Sahayatra Microfinance Bittiya Sanstha Ltd.',
	"JSLBB" : 'Janautthan Samudayic Laghubitta Bikas Bank Ltd.',
	"KMFL" : 'Kisan Microfinance Bittiya Sanstha Ltd.',
	"WOMI" : 'Womi Microfinance Bittiya Sanstha Ltd.',
	"VLBS" : 'Vijaya laghubitta Bittiya Sanstha Ltd.',
	"RSDC" : 'RSDC Laghubitta Bittiya Sanstha Ltd.',
	"NMBMF" : 'NMB Microfinance Bittiya Sanstha Ltd.',
	"MERO" : 'Mero Microfinance Bittiya Sanstha Ltd.',
	"NMFBS" : 'National Microfinance Bittiya Sanstha Ltd.',
	"SLBS" : 'Suryodaya Laghubitta Bittiya Sanstha Ltd.',
	"CLBSL" : 'Civil Laghubitta Bittiya Sanstha Ltd.',
	"FOWAD" : 'Forward Community Microfinance Bittiya Sanstha Ltd.',
	"SMATA" : 'Samata Microfinance Bittiya Sanstha Ltd.',
	"SDESI" : 'Swadeshi Laghubitta Bittiya Sanstha Ltd.',
	"MSLB" : 'Mahuli Samudayik Laghubitta Sanstha Ltd.',
	"GILB" : 'Global IME Laghubitta Bittiya Sanstha Ltd.',
	"SMB" : 'Support Microfinance Bittiya Sanstha Ltd.',
	"UMB" : 'Unnati Micorfinance Bittiya Sanstha Ltd.',
	"AMFI" : 'Arambha Microfinance Bittiya Sanstha Ltd.',
	"GBLBS" : 'Grameen Bikas Laghubitta Bittiya Sanstha Ltd.',
	"NSEWA" : 'Nepal Seva Laghubitta Bittiya Sanstha Ltd.',
	"NBF1" : 'Nabil Balance Fund 1',
	"SIGS1" : 'Siddhartha Investment Growth Scheme-1',
	"NCMMF" : 'NCM Mutual Fund',
	"SEOS" : 'Siddhartha Equity Orineted Scheme',
	"NMBSF1" : 'NMB Sulav Investment Fund-1',
	"NIBSF1" : 'NIBL Samriddhi Fund 1',
	"LVF1" : 'Laxmi Value Fund-1',
	"SBLD78" : '7.5% sbl debenture',
	"GIMES1" : 'Global IME Samunnat Scheme-1',
	"NEF" : 'Nabil Equity Fund',
	"NIBLPF" : 'NIBL Pragati Fund',
	"NMBHF1" : 'NMB Hybrid Fund L-1',
	"LEMF" : 'Laxmi Equity Fund',
	"SEF" : 'Siddhartha Equity Fund',
	"SEF" : 'Siddhartha Equity Fund',
	"SAEF" : 'Sanima Equity Fund',
	"NICGF" : 'NIC Asia Growth Fund',
	"CMF1" : 'Citizens Mutual Fund -1',
	"CIT" : 'Citizen Investment Trust',
	"NFD" : 'Nepal Film Development Company Limited',
	"NTC" : 'Nepal Doorsanchar Comapany Limited',
	"ESC" : 'National Pro. And Eco. Development Centre',
	"HIDCL" : 'Jalabidyut Lagani tatha Bikas Co. Ltd.',
	"KRBLPO" : 'Karnali Development Bank Limited Promoter Share',
	"VSDBLP" : 'Vibor Society Development Bank Limited Promoter Share',
	"ODBLPO" : 'Om Development Bank Ltd. Promoter',
	"KSBBLP" : 'Kamana Sewa Bikas Bank Limited Promoter Share',
	"MLBLPO" : 'Mahalxmi Bikas Bank Ltd. Promotor Share',
	"BFCPO" : 'Best Finance Co. Limited Promoter Share',
	"MPFLPO" : 'Multipurpose Finance Company  Limited Promoter Share',
	"LBBLPO" : 'Lumbini Bikas Bank Ltd. Promoter Share',
	"CEFLPO" : 'City Express Finance Co. Ltd. Promoter Share',
	"IGIPO" : 'IME General Insurance  Ltd. Promoter Share',
	"EBLCP" : 'Everest Bank Limited Con. Pref.',
	"TRHPR" : 'Taragaon Regency Hotels Ltd. Preference Share',
	"ACEDPO" : 'ACE Development Bank Limited Promoter Share',
	"AEFLPO" : 'Alpic Everest Finance Limited Promoter Share',
	"AICPO" : 'Alliance Insurance Company Ltd. Promoter',
	"ALICLP" : 'Asian Life Insurance Co. Ltd Promoter Share',
	"AXISP" : 'Axis Development Bank Limited Promoter Share',
	"BBBLNP" : 'Bagheshowari Development Bank Ltd. Promoer Share',
	"BBBLPO" : 'Bhrikuti Bikash Bank Limited Promoter Share',
	"BFLPO" : 'Butwal Finance Limited Promoter Share',
	"BLDBLP" : 'Biratlaxmi Bikas Bank Limited Promoter Share',
	"BOKPO" : 'Bank of Kathmandu Limited Promoter Share',
	"CDBLPO" : 'City Development Bank Ltd. Promoter',
	"CEDBLP" : 'Clean Energy Development Bank Ltd. Promoter Share',
	"CMBFLP" : 'Capital Merchant Bank. & Fin. Promoter Share',
	"CMBFPO" : 'CMB Finance Ltd. Promoter Share',
	"CMBSLp" : 'Civil Merchant Bittiya Sanstha Limited Promoter Share',
	"CZBILP" : 'Citizens Bank Internatioal Limited Promoter Share',
	"EBLPO" : 'Everest Bank Limited Promoter Share',
	"EFLPO" : 'Everest Finance Limited Promoter Share',
	"FFCLPO" : 'Fewa Finance Company Limited Promoter Share',
	"GBIMEP" : 'Global IME Bank Limited Promoter Share',
	"GFCLPO" : 'Goodwill Finance Company Limited Promoter Share',
	"GFLKPO" : 'Gorkha Finance Limited Promoter Share',
	"GFLPO" : 'General Finance Limited Promoter Share',
	"GRANDP" : 'Grand Bank Limited Promoter Share',
	"GSDBLP" : 'Gaurishankar Development Bank Ltd. Promoter Share',
	"HBDLPO" : 'H & B Development Bank Limited Promoter Share',
	"HBLPO" : 'Himalayan Bank Limited Promoter Share',
	"ICFCPO" : 'ICFC Finance Limited Promotor Share',
	"IDBLPO" : 'Infrastructure Development Bank Limited Promoter Share',
	"IFILPO" : 'Imperial Finance Ltd Promoter Share',
	"IMEFIP" : 'IME Financial Institution Promoter Share',
	"JBBLPO" : 'Jyoti Bikash Bank Ltd. Promoter Share',
	"JFLPO" : 'Janaki Finance Limited Promoter Share',
	"KAFILP" : 'Kaski Finanace Ltd. Promoter',
	"KBBLPO" : 'Kailash Bikas Bank Limited Promoter Share',
	"KBLPO" : 'Kumari Bank Limited Promotor Share',
	"KDBLPO" : 'Kasthamandap Dev. Bank Limited Promoter Share',
	"KFLPO" : 'Kathmandu Finance Ltd. Promoter Share',
	"KISTPO" : 'KIST Bank Limited Promoter Share',
	"LBLPO" : 'Laxmi Bank Limited Promoter Share',
	"LFCPO" : 'Lalitpur Finance Co. Ltd. Promoter Share',
	"LFLCPO" : 'Lumbini Finance Ltd Promoter Share',
	"LUBLPO" : 'Lumbini Bank Limited Promotor Share',
	"MBBLPO" : 'Mahakali Bikas Bank Ltd. Promoter',
	"MBLPO" : 'Machhapuchchhre Bank Limited Promotor Share',
	"MDBLPO" : 'Malika Development Bank Limited Promoter Share',
	"MFLPO" : 'Maha Laxmi Finance Company Limited Promoter Share',
	"NABBPO" : 'Nepal Aawas Finance Limited Promoter Share',
	"NABILP" : 'NABIL Bank Limited Promotor Share',
	"NBBPO" : 'Nepal Bangladesh Bank Limited Promoter Share',
	"NCCBPO" : 'Nepal Credit & Commercial Bank Ltd. Promoter Share',
	"NCMPO" : 'N.I.D.C Capital Markets Ltd. Promoter Share',
	"NDBPO" : 'Nepal Development Bank Limited Promoter Share',
	"NDEPPO" : 'NDEP Development Bank Ltd. Promoter Share',
	"NEFLPO" : 'Nepal Express Finance Limited Promoter Share',
	"NHMFPO" : 'Nepal Housing & Merchant Co. Ltd. Promoter Share',
	"NIBPO" : 'Nepal Investment Bank Ltd. Promoter Share',
	"NICAP" : 'NIC Asia Bank Limted Promoter Share',
	"NLICLP" : 'National Life Insurance Co. Ltd. Promoter Share',
	"NLICP" : 'Nepal Life Insurance Co. Ltd. Promoter',
	"NMBPO" : 'NMB Bank Limited Promoter Share',
	"NNFCPO" : 'Narayani National Finance Company Limited Promoter Share',
	"NSMPO" : 'Nepal Share Markets Limited Promoter Share',
	"OFLPO" : 'Om Finance Limited Promoter Share',
	"PCBLP" : 'Prime Commercial Bank Limited Promoter Share',
	"PDBLPO" : 'Paschimanchal Bikash Bank Ltd. Promoter Share',
	"PFCLPO" : 'Peoples Finance Limited Promoter Share',
	"PFLBSP" : 'Patan Finance Limited Promoter Share',
	"PFLPO" : 'Pokhara Finance Company Limited Promoter Share',
	"PRFLPO" : 'Prabhu Finance Ltd. Promoter Share',
	"PROFLP" : 'Progressive Finance Limited Promoter Share',
	"RIBSLP" : 'Reliable Finance Co. Ltd. Promoter Share',
	"RMBFPO" : 'Royal Merchant Bank & Finance Co. Ltd. Promoter Share',
	"SBBLJP" : 'Sahayogi Bikas Bank Ltd. Promoter Share',
	"SBBLPO" : 'Sanima Bank Limited Promoter Share',
	"SBIPO" : 'Nepal SBI Bank Ltd. Promoter Share',
	"SBLPO" : 'Siddhartha Bank Limited Promoter Share',
	"SDBLPO" : 'Siddhartha Development Bank Limited Promoter Share',
	"SETIPO" : 'Seti Finance Ltd. Promoter Share',
	"SEWAPO" : 'Sewa Bikas Bank Ltd. Promoter',
	"SFCPO" : 'Samjhana Finace Co. Ltd. Promoter Share',
	"SFFILP" : 'Shrijana Finance Limited Promoter Share',
	"SFLPO" : 'Siddhartha Finance Limited Promoter Share',
	"SIFCPO" : 'Shree Investment & Finance Company Limited Promoter Share',
	"SLICLP" : 'Surya Life Insurance Co. Ltd. Promoter Share',
	"SRBLPO" : 'Sunrise Bank Ltd Promoter Share',
	"STFLPO" : 'Standard Finance Limited Promoter Share',
	"SUBBLP" : 'Subbecha Bikas Bank Ltd. Promoter Share',
	"SUPRMP" : 'Supreme Development Bank Ltd. Promoter Share',
	"SWBBLP" : 'Swabalamban Bikas Bank Limited Promoter Share',
	"TBBLP" : 'Triveni Bikas Bank Limited Promoter Share',
	"TNBLPO" : 'Tinau Development Bank Limited Promoter',
	"UFCLPO" : 'Union Finance Co. Ltd. Promoter Share',
	"UFLKPO" : 'Universal Finance Limited Promoter Share',
	"UFLPO" : 'United Finance Company Limited Promoter Share',
	"WMBFPO" : 'World Merchant Banking & Finance Limited Promoter Share',
	"YFLPO" : 'Yeti Finance Limited Promoter Share',
	"UFILPO" : 'Unique Finance Limited Promoter Share',
	"MDBPO" : 'Miteri Development Bank Limited Promoter Share',
	"PSDBLP" : 'Pashupati Development Bank Limited Promoter Share',
	"PFILPO" : 'Prudential Finance Co. Ltd. Promoter',
	"HAMAPO" : 'Hama Merchant & Finance Ltd. Promoter Share',
	"EDBLPO" : 'Excel Development Bank Ltd. Promoter Share',
	"NILPO" : 'Neco Insurace Co. Ltd. Promoter',
	"SICPO" : 'Sagarmatha Insurance Co. Ltd. Promoter Share',
	"YETIPO" : 'Yeti Development Bank Limited Promotor Share',
	"GLICLP" : 'Guras Life Insurance Company Ltd. Promoter Share',
	"ARDBLP" : 'Araniko Development Bank Limited Promoter Share',
	"GBBLPO" : 'Garima Bikas Bank Limited Promoter Share',
	"SYFLPO" : 'Synergy Finance Limited Promoter Share',
	"VBBLPO" : 'Vibor Bikas Bank Limited Promoter Share',
	"SICLPO" : 'Shikhar Insurance Company Limited Promoter Share',
	"BSBLPO" : 'Bishwa Bikas Bank Limited Promoter Share',
	"REDBLP" : 'Reliable Development Bank Ltd. Promoter Share',
	"SILPO" : 'Siddhartha Insurance Limited Promoter Share',
	"BHBLPO" : 'Bhargav Bikash Bank Ltd. Promoter Share',
	"PRVUPO" : 'Prabhu Bank Limited Promoter Share',
	"WDBLPO" : 'Western Development Bank Limited Promoter Share',
	"NBILPO" : 'NB Insurance Company Limited. Promoter Share',
	"RBSPO" : 'Rastriya Beema Sansthan Promoter Share',
	"CSDBLP" : 'Cosmos Development Bank Ltd. Promoter Share',
	"CNDBLP" : 'Country Development Bank Limited Promoter Share',
	"EKBLPO" : 'Ekata Bikas Bank Ltd. Promoter Share',
	"HAMROP" : 'Hamro Bikas Bank Limited Promoter Share',
	"KNBLPO" : 'Kankai Bikas Bank Ltd. Promoter Share',
	"LLBSPO" : 'Laxmi Laghubitta Bittiya Sanstha Limited Promoter Share',
	"MNBBLP" : 'Muktinath Bikas Bank Limited Promoter Share',
	"NNLBPO" : 'Naya Nepal Laghubitta Bikas Bank Ltd. Promoter Share',
	"BUDBLP" : 'Business Universal Development Bank Ltd. Promoter Share',
	"PFCPO" : 'Paschimanchal Finance Co. Ltd. Promoter Share',
	"JHBLPO" : 'Jhimruk Bikas Bank Ltd. Promoter Share',
	"NBBLPO" : 'NagBeli LaghuBitta Bikas Bank Ltd. Promoter Share',
	"NFSPO" : 'Nepal Finance Ltd. Promoter Share',
	"PICLPO" : 'Prudential Insurance Co. Ltd. Promoter Share',
	"RLFLPO" : 'Reliance Lotus Finance Ltd. Promoter Share',
	"ALDBLP" : 'Alpine Development Bank Limited Promoter Share',
	"APEXPO" : 'Apex Development Bank Ltd. Promoter Share',
	"CCBLPO" : 'Century Commercial Bank Limited Promoter Share',
	"CBLPO" : 'Civil Bank Ltd Promoter Share',
	"GDBLPO" : 'Gandaki Bikas Bank Limited Promoter Share',
	"GABLPO" : 'Gaumukhee Bikas Bank Ltd. Promoter Share',
	"JBNLPO" : 'Janata Bank Nepal Ltd. Promoter Share',
	"JEFLPO" : 'Jebils Finance Ltd. Promoter Share',
	"MSBBLP" : 'Manaslu Bikas Bank Limited Promoter Share',
	"MEGAPO" : 'Mega Bank Nepal Limited Promoter Share',
	"MIDBLP" : 'Mission Development Bank Ltd. Promoter Share',
	"NBSLPO" : 'Namaste Bittiya Sanstha Ltd. Promoter Share',
	"NLBBLP" : 'Nerude Laghubita Bikas Bank Limited Promoter Share',
	"NIDCPO" : 'N.I.D.C Development Bank Ltd. Promoter Share',
	"NUBLPO" : 'Nirdhan Utthan Bank Limited Promoter Share',
	"PRDBLP" : 'Professional Diyalo Bikas Bank Ltd. Promoter Share',
	"RMDCPO" : 'Rural Microfinance Development Centre Limited Promoter Share',
	"SKBBLP" : 'Sana Kisan Bikas Bank Ltd Promoter Share',
	"SHINEP" : 'Shine Resunga Development Bank Limited Promoter Share',
	"SINDUP" : 'Sindhu Bikash Bank Limited Promoter Share',
	"SCBPO" : 'Standard Chartered Bank Limited Promoter Share',
	"SMFDBP" : 'Summit Micro Finance Development Bank Ltd. Promoter Share',
	"CFCLPO" : 'Central Finance Company Limited Promoter Share',
	"KMBLPO" : 'Kamana Bikas Bank Limited Promoter Share',
	"RBCLPO" : 'Rastriya Beema Company Limited Promoter Share',
	"KMCDBP" : 'Kalika Microcredit Development Bank Ltd. Promoter Share',
	"PADBLP" : 'Pacific Development Bank Ltd. Promoter Share',
	"BGDBLP" : 'Bagmati Development Bank Ltd. Promoter Share',
	"PRINPO" : 'Prabhu Insurance Company Ltd. Promoter',
	"DDBLPO" : 'Deprosc LaghuBitta Promoter Share',
	"INDBPO" : 'Innovative Development Bank Ltd. Promoter Share',
	"NLGPO" : 'NLG Insurance Company Ltd. Promoter Share',
	"SODBLP" : 'Society Development Bank Limited Promoter Share',
	"ARUNPO" : 'Arun Finance Limited Promoter Share',
	"DBBLPO" : 'Dev BikasBank Ltd. Promoter Share',
	"ILFCPO" : 'International Leasing & Finance Co. Ltd. Promoter Share',
	"NICLPO" : 'Nepal Insurance Co. Ltd Promoter Share',
	"TDBLPO" : 'Tourism Development Bank Limited Prmoter Share',
	"LICNPO" : 'Life Insurance Co. Nepal Promoter Share',
	"CBBLPO" : 'Chhimek Laghubitta Bikas Bank Limited Promoter Share',
	"NCDBPO" : 'Nepal Community Development Bank Ltd. Promoter Share',
	"EICPO" : 'Everest Insurance Company Limited Promoter Share',
	"HGIPO" : 'Himalayan General Insurance Compny Limited Promoter Share',
	"LGILPO" : 'Lumbini General Insurance Co. Ltd. Promoter Share',
	"PLICPO" : 'Prime Life Insurance Company Limited Promoter Share',
	"MLBBLP" : 'Mithila Laghubitta Bikas Bank Limited Promoter Share',
	"SADBLP" : 'Shangrila Development Bank Ltd. Promoter Share',
	"INDBLP" : 'International Development Bank Ltd Promoter Share',
	"KADBLP" : 'Kanchan Development Bank Limited Promoter Share',
	"MMFDBP" : 'Mirmire Microfinance Development Bank Ltd. Promoter Share',
	"PICPO" : 'Premier Insurance Co. Ltd. Promoter Share',
	"PURBLP" : 'Purnima Bikas Bank Limited Promoter Share',
	"SAFLPO" : 'Sagarmatha Finance Limited Promoter Share',
	"VLBSPO" : 'Vijaya laghubitta Bittiya Sanstha Ltd. Promoter Share',
	"JSLBBP" : 'Janautthan Samudayic Laghubitta Bikas Bank Ltd. Promoter Share',
	"KCDBLP" : 'Kalinchowk Development Bank Ltd. Promoter Share',
	"RBBBLP" : 'Rapti Bheri Bikas Bank Ltd. Promoter Share',
	"SLBBLP" : 'Swarojgar Laghu Bitta Bikas Bank Ltd. Promoter Share',
	"WOMIPO" : 'Womi Microfinance Bittiya Sanstha Limited Promoter Share',
	"FBBLPO" : 'Fewa Bikas Bank Ltd. Promoter Share',
	"CVMFPO" : 'Clean Village Microfinance Bittiya Sanstha Ltd. Promoter Share',
	"FMDBLP" : 'First Micro Finance Development Bank Ltd. Promoter Share',
	"ILFCMP" : 'ILFCO Microfinance Bittiya Sanstha Ltd. Promoter Share',
	"MMDBLP" : 'Mount Makalu Development Bank Ltd. Promoter Share',
	"BFCLPO" : 'Bhaktapur Finance Co. Ltd. Promoter Share',
	"GMFILP" : 'Guheyshwori Merchant & Finance Ltd. Promoter Share',
	"KEBLPO" : 'Kabeli BIkas Bank Ltd. Promoter Share',
	"KKBLPO" : 'Kankre Bihar Bikash Bank Limited Promoter Share',
	"UICPO" : 'United Insurance Co. (Nepal) Ltd. Promoter Share',
	"MFILPO" : 'Manjushree Financial Institution Limited Promoter Share',
	"RMFLPO" : 'Reliable Microfinance Bittiya Sanstha Ltd. Promoter Share',
	"BBC" : 'Bishal Bazar Company Limited',
	}

def know_index(name):
	if name in identity:
		return str(identity[name])
	else:
		return "UNKNOWN"
